version: '3.8'

services:
  node:
    build: .
    container_name: node_container
    depends_on:
      - postgres
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    ports:
      - ${PORT}:${PORT}

  postgres:
    image: postgres:15.1
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-db:
  pgadmin-data:
